sudo: false

language: erlang
otp_release:
   - 19.0

addons:
  apt:
    packages:
      - build-essential
      - dbus
      - python3
      - python3-gi
      - python3-dbus
      - python3-pycurl
      - libglib2.0-0

install:
  - export
  - "make"

script:
  - "make tests"

notifications:
  email:
    on_success: change
    on_failure: always
